source "https://rubygems.org"

gem "jekyll", "~> 3.9.0"
gem "jekyll-feed", "~> 0.15.1"
gem "jekyll-seo-tag", "~> 2.7.1"
gem "jekyll-sitemap", "~> 1.4.0"
gem "jekyll-paginate", "~> 1.1.0"
gem "jekyll-pandoc", "~> 2.0.1"
gem "kramdown-parser-gfm", "~> 1.1.0"
gem "webrick", "~> 1.7"
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
